# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-4.0.0-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-4.0.0-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roman/Projects/plot-cv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roman/Projects/plot-cv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@echo "Running external command ..."
	cd /home/roman/Projects/plot-cv && /opt/cmake-4.0.0-linux-x86_64/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@echo "Running external command ..."
	cd /home/roman/Projects/plot-cv && /opt/cmake-4.0.0-linux-x86_64/bin/cpack --config ./CPackSourceConfig.cmake /home/roman/Projects/plot-cv/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Running external command ..."
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo "Running external command ..."
	/opt/cmake-4.0.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Projects/plot-cv/CMakeFiles /home/roman/Projects/plot-cv/qjs-opencv//CMakeFiles/progress.marks
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs-opencv/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roman/Projects/plot-cv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs-opencv/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs-opencv/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs-opencv/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -P /home/roman/Projects/plot-cv/CMakeFiles/VerifyGlobs.cmake
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
qjs-opencv/CMakeFiles/quickjs-opencv.dir/rule:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qjs-opencv/CMakeFiles/quickjs-opencv.dir/rule
.PHONY : qjs-opencv/CMakeFiles/quickjs-opencv.dir/rule

# Convenience name for target.
quickjs-opencv: qjs-opencv/CMakeFiles/quickjs-opencv.dir/rule
.PHONY : quickjs-opencv

# fast build rule for target.
quickjs-opencv/fast:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/build
.PHONY : quickjs-opencv/fast

algorithms/dominant_colors_grabber.o: algorithms/dominant_colors_grabber.cpp.o
.PHONY : algorithms/dominant_colors_grabber.o

# target to build an object file
algorithms/dominant_colors_grabber.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/algorithms/dominant_colors_grabber.cpp.o
.PHONY : algorithms/dominant_colors_grabber.cpp.o

algorithms/dominant_colors_grabber.i: algorithms/dominant_colors_grabber.cpp.i
.PHONY : algorithms/dominant_colors_grabber.i

# target to preprocess a source file
algorithms/dominant_colors_grabber.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/algorithms/dominant_colors_grabber.cpp.i
.PHONY : algorithms/dominant_colors_grabber.cpp.i

algorithms/dominant_colors_grabber.s: algorithms/dominant_colors_grabber.cpp.s
.PHONY : algorithms/dominant_colors_grabber.s

# target to generate assembly for a file
algorithms/dominant_colors_grabber.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/algorithms/dominant_colors_grabber.cpp.s
.PHONY : algorithms/dominant_colors_grabber.cpp.s

gifenc/gifenc.o: gifenc/gifenc.c.o
.PHONY : gifenc/gifenc.o

# target to build an object file
gifenc/gifenc.c.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/gifenc/gifenc.c.o
.PHONY : gifenc/gifenc.c.o

gifenc/gifenc.i: gifenc/gifenc.c.i
.PHONY : gifenc/gifenc.i

# target to preprocess a source file
gifenc/gifenc.c.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/gifenc/gifenc.c.i
.PHONY : gifenc/gifenc.c.i

gifenc/gifenc.s: gifenc/gifenc.c.s
.PHONY : gifenc/gifenc.s

# target to generate assembly for a file
gifenc/gifenc.c.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/gifenc/gifenc.c.s
.PHONY : gifenc/gifenc.c.s

js_affine3.o: js_affine3.cpp.o
.PHONY : js_affine3.o

# target to build an object file
js_affine3.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_affine3.cpp.o
.PHONY : js_affine3.cpp.o

js_affine3.i: js_affine3.cpp.i
.PHONY : js_affine3.i

# target to preprocess a source file
js_affine3.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_affine3.cpp.i
.PHONY : js_affine3.cpp.i

js_affine3.s: js_affine3.cpp.s
.PHONY : js_affine3.s

# target to generate assembly for a file
js_affine3.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_affine3.cpp.s
.PHONY : js_affine3.cpp.s

js_algorithms.o: js_algorithms.cpp.o
.PHONY : js_algorithms.o

# target to build an object file
js_algorithms.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_algorithms.cpp.o
.PHONY : js_algorithms.cpp.o

js_algorithms.i: js_algorithms.cpp.i
.PHONY : js_algorithms.i

# target to preprocess a source file
js_algorithms.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_algorithms.cpp.i
.PHONY : js_algorithms.cpp.i

js_algorithms.s: js_algorithms.cpp.s
.PHONY : js_algorithms.s

# target to generate assembly for a file
js_algorithms.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_algorithms.cpp.s
.PHONY : js_algorithms.cpp.s

js_aruco.o: js_aruco.cpp.o
.PHONY : js_aruco.o

# target to build an object file
js_aruco.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_aruco.cpp.o
.PHONY : js_aruco.cpp.o

js_aruco.i: js_aruco.cpp.i
.PHONY : js_aruco.i

# target to preprocess a source file
js_aruco.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_aruco.cpp.i
.PHONY : js_aruco.cpp.i

js_aruco.s: js_aruco.cpp.s
.PHONY : js_aruco.s

# target to generate assembly for a file
js_aruco.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_aruco.cpp.s
.PHONY : js_aruco.cpp.s

js_barcode_detector.o: js_barcode_detector.cpp.o
.PHONY : js_barcode_detector.o

# target to build an object file
js_barcode_detector.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_barcode_detector.cpp.o
.PHONY : js_barcode_detector.cpp.o

js_barcode_detector.i: js_barcode_detector.cpp.i
.PHONY : js_barcode_detector.i

# target to preprocess a source file
js_barcode_detector.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_barcode_detector.cpp.i
.PHONY : js_barcode_detector.cpp.i

js_barcode_detector.s: js_barcode_detector.cpp.s
.PHONY : js_barcode_detector.s

# target to generate assembly for a file
js_barcode_detector.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_barcode_detector.cpp.s
.PHONY : js_barcode_detector.cpp.s

js_bg_subtractor.o: js_bg_subtractor.cpp.o
.PHONY : js_bg_subtractor.o

# target to build an object file
js_bg_subtractor.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_bg_subtractor.cpp.o
.PHONY : js_bg_subtractor.cpp.o

js_bg_subtractor.i: js_bg_subtractor.cpp.i
.PHONY : js_bg_subtractor.i

# target to preprocess a source file
js_bg_subtractor.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_bg_subtractor.cpp.i
.PHONY : js_bg_subtractor.cpp.i

js_bg_subtractor.s: js_bg_subtractor.cpp.s
.PHONY : js_bg_subtractor.s

# target to generate assembly for a file
js_bg_subtractor.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_bg_subtractor.cpp.s
.PHONY : js_bg_subtractor.cpp.s

js_calib3d.o: js_calib3d.cpp.o
.PHONY : js_calib3d.o

# target to build an object file
js_calib3d.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_calib3d.cpp.o
.PHONY : js_calib3d.cpp.o

js_calib3d.i: js_calib3d.cpp.i
.PHONY : js_calib3d.i

# target to preprocess a source file
js_calib3d.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_calib3d.cpp.i
.PHONY : js_calib3d.cpp.i

js_calib3d.s: js_calib3d.cpp.s
.PHONY : js_calib3d.s

# target to generate assembly for a file
js_calib3d.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_calib3d.cpp.s
.PHONY : js_calib3d.cpp.s

js_clahe.o: js_clahe.cpp.o
.PHONY : js_clahe.o

# target to build an object file
js_clahe.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_clahe.cpp.o
.PHONY : js_clahe.cpp.o

js_clahe.i: js_clahe.cpp.i
.PHONY : js_clahe.i

# target to preprocess a source file
js_clahe.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_clahe.cpp.i
.PHONY : js_clahe.cpp.i

js_clahe.s: js_clahe.cpp.s
.PHONY : js_clahe.s

# target to generate assembly for a file
js_clahe.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_clahe.cpp.s
.PHONY : js_clahe.cpp.s

js_contour.o: js_contour.cpp.o
.PHONY : js_contour.o

# target to build an object file
js_contour.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_contour.cpp.o
.PHONY : js_contour.cpp.o

js_contour.i: js_contour.cpp.i
.PHONY : js_contour.i

# target to preprocess a source file
js_contour.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_contour.cpp.i
.PHONY : js_contour.cpp.i

js_contour.s: js_contour.cpp.s
.PHONY : js_contour.s

# target to generate assembly for a file
js_contour.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_contour.cpp.s
.PHONY : js_contour.cpp.s

js_cv.o: js_cv.cpp.o
.PHONY : js_cv.o

# target to build an object file
js_cv.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_cv.cpp.o
.PHONY : js_cv.cpp.o

js_cv.i: js_cv.cpp.i
.PHONY : js_cv.i

# target to preprocess a source file
js_cv.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_cv.cpp.i
.PHONY : js_cv.cpp.i

js_cv.s: js_cv.cpp.s
.PHONY : js_cv.s

# target to generate assembly for a file
js_cv.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_cv.cpp.s
.PHONY : js_cv.cpp.s

js_draw.o: js_draw.cpp.o
.PHONY : js_draw.o

# target to build an object file
js_draw.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_draw.cpp.o
.PHONY : js_draw.cpp.o

js_draw.i: js_draw.cpp.i
.PHONY : js_draw.i

# target to preprocess a source file
js_draw.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_draw.cpp.i
.PHONY : js_draw.cpp.i

js_draw.s: js_draw.cpp.s
.PHONY : js_draw.s

# target to generate assembly for a file
js_draw.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_draw.cpp.s
.PHONY : js_draw.cpp.s

js_fast_line_detector.o: js_fast_line_detector.cpp.o
.PHONY : js_fast_line_detector.o

# target to build an object file
js_fast_line_detector.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_fast_line_detector.cpp.o
.PHONY : js_fast_line_detector.cpp.o

js_fast_line_detector.i: js_fast_line_detector.cpp.i
.PHONY : js_fast_line_detector.i

# target to preprocess a source file
js_fast_line_detector.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_fast_line_detector.cpp.i
.PHONY : js_fast_line_detector.cpp.i

js_fast_line_detector.s: js_fast_line_detector.cpp.s
.PHONY : js_fast_line_detector.s

# target to generate assembly for a file
js_fast_line_detector.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_fast_line_detector.cpp.s
.PHONY : js_fast_line_detector.cpp.s

js_feature2d.o: js_feature2d.cpp.o
.PHONY : js_feature2d.o

# target to build an object file
js_feature2d.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_feature2d.cpp.o
.PHONY : js_feature2d.cpp.o

js_feature2d.i: js_feature2d.cpp.i
.PHONY : js_feature2d.i

# target to preprocess a source file
js_feature2d.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_feature2d.cpp.i
.PHONY : js_feature2d.cpp.i

js_feature2d.s: js_feature2d.cpp.s
.PHONY : js_feature2d.s

# target to generate assembly for a file
js_feature2d.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_feature2d.cpp.s
.PHONY : js_feature2d.cpp.s

js_filenode.o: js_filenode.cpp.o
.PHONY : js_filenode.o

# target to build an object file
js_filenode.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_filenode.cpp.o
.PHONY : js_filenode.cpp.o

js_filenode.i: js_filenode.cpp.i
.PHONY : js_filenode.i

# target to preprocess a source file
js_filenode.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_filenode.cpp.i
.PHONY : js_filenode.cpp.i

js_filenode.s: js_filenode.cpp.s
.PHONY : js_filenode.s

# target to generate assembly for a file
js_filenode.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_filenode.cpp.s
.PHONY : js_filenode.cpp.s

js_filestorage.o: js_filestorage.cpp.o
.PHONY : js_filestorage.o

# target to build an object file
js_filestorage.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_filestorage.cpp.o
.PHONY : js_filestorage.cpp.o

js_filestorage.i: js_filestorage.cpp.i
.PHONY : js_filestorage.i

# target to preprocess a source file
js_filestorage.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_filestorage.cpp.i
.PHONY : js_filestorage.cpp.i

js_filestorage.s: js_filestorage.cpp.s
.PHONY : js_filestorage.s

# target to generate assembly for a file
js_filestorage.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_filestorage.cpp.s
.PHONY : js_filestorage.cpp.s

js_fisheye.o: js_fisheye.cpp.o
.PHONY : js_fisheye.o

# target to build an object file
js_fisheye.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_fisheye.cpp.o
.PHONY : js_fisheye.cpp.o

js_fisheye.i: js_fisheye.cpp.i
.PHONY : js_fisheye.i

# target to preprocess a source file
js_fisheye.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_fisheye.cpp.i
.PHONY : js_fisheye.cpp.i

js_fisheye.s: js_fisheye.cpp.s
.PHONY : js_fisheye.s

# target to generate assembly for a file
js_fisheye.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_fisheye.cpp.s
.PHONY : js_fisheye.cpp.s

js_highgui.o: js_highgui.cpp.o
.PHONY : js_highgui.o

# target to build an object file
js_highgui.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_highgui.cpp.o
.PHONY : js_highgui.cpp.o

js_highgui.i: js_highgui.cpp.i
.PHONY : js_highgui.i

# target to preprocess a source file
js_highgui.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_highgui.cpp.i
.PHONY : js_highgui.cpp.i

js_highgui.s: js_highgui.cpp.s
.PHONY : js_highgui.s

# target to generate assembly for a file
js_highgui.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_highgui.cpp.s
.PHONY : js_highgui.cpp.s

js_imgproc.o: js_imgproc.cpp.o
.PHONY : js_imgproc.o

# target to build an object file
js_imgproc.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_imgproc.cpp.o
.PHONY : js_imgproc.cpp.o

js_imgproc.i: js_imgproc.cpp.i
.PHONY : js_imgproc.i

# target to preprocess a source file
js_imgproc.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_imgproc.cpp.i
.PHONY : js_imgproc.cpp.i

js_imgproc.s: js_imgproc.cpp.s
.PHONY : js_imgproc.s

# target to generate assembly for a file
js_imgproc.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_imgproc.cpp.s
.PHONY : js_imgproc.cpp.s

js_keypoint.o: js_keypoint.cpp.o
.PHONY : js_keypoint.o

# target to build an object file
js_keypoint.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_keypoint.cpp.o
.PHONY : js_keypoint.cpp.o

js_keypoint.i: js_keypoint.cpp.i
.PHONY : js_keypoint.i

# target to preprocess a source file
js_keypoint.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_keypoint.cpp.i
.PHONY : js_keypoint.cpp.i

js_keypoint.s: js_keypoint.cpp.s
.PHONY : js_keypoint.s

# target to generate assembly for a file
js_keypoint.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_keypoint.cpp.s
.PHONY : js_keypoint.cpp.s

js_libcamera_app.o: js_libcamera_app.cpp.o
.PHONY : js_libcamera_app.o

# target to build an object file
js_libcamera_app.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_libcamera_app.cpp.o
.PHONY : js_libcamera_app.cpp.o

js_libcamera_app.i: js_libcamera_app.cpp.i
.PHONY : js_libcamera_app.i

# target to preprocess a source file
js_libcamera_app.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_libcamera_app.cpp.i
.PHONY : js_libcamera_app.cpp.i

js_libcamera_app.s: js_libcamera_app.cpp.s
.PHONY : js_libcamera_app.s

# target to generate assembly for a file
js_libcamera_app.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_libcamera_app.cpp.s
.PHONY : js_libcamera_app.cpp.s

js_line.o: js_line.cpp.o
.PHONY : js_line.o

# target to build an object file
js_line.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line.cpp.o
.PHONY : js_line.cpp.o

js_line.i: js_line.cpp.i
.PHONY : js_line.i

# target to preprocess a source file
js_line.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line.cpp.i
.PHONY : js_line.cpp.i

js_line.s: js_line.cpp.s
.PHONY : js_line.s

# target to generate assembly for a file
js_line.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line.cpp.s
.PHONY : js_line.cpp.s

js_line_iterator.o: js_line_iterator.cpp.o
.PHONY : js_line_iterator.o

# target to build an object file
js_line_iterator.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line_iterator.cpp.o
.PHONY : js_line_iterator.cpp.o

js_line_iterator.i: js_line_iterator.cpp.i
.PHONY : js_line_iterator.i

# target to preprocess a source file
js_line_iterator.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line_iterator.cpp.i
.PHONY : js_line_iterator.cpp.i

js_line_iterator.s: js_line_iterator.cpp.s
.PHONY : js_line_iterator.s

# target to generate assembly for a file
js_line_iterator.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line_iterator.cpp.s
.PHONY : js_line_iterator.cpp.s

js_line_segment_detector.o: js_line_segment_detector.cpp.o
.PHONY : js_line_segment_detector.o

# target to build an object file
js_line_segment_detector.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line_segment_detector.cpp.o
.PHONY : js_line_segment_detector.cpp.o

js_line_segment_detector.i: js_line_segment_detector.cpp.i
.PHONY : js_line_segment_detector.i

# target to preprocess a source file
js_line_segment_detector.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line_segment_detector.cpp.i
.PHONY : js_line_segment_detector.cpp.i

js_line_segment_detector.s: js_line_segment_detector.cpp.s
.PHONY : js_line_segment_detector.s

# target to generate assembly for a file
js_line_segment_detector.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_line_segment_detector.cpp.s
.PHONY : js_line_segment_detector.cpp.s

js_mat.o: js_mat.cpp.o
.PHONY : js_mat.o

# target to build an object file
js_mat.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_mat.cpp.o
.PHONY : js_mat.cpp.o

js_mat.i: js_mat.cpp.i
.PHONY : js_mat.i

# target to preprocess a source file
js_mat.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_mat.cpp.i
.PHONY : js_mat.cpp.i

js_mat.s: js_mat.cpp.s
.PHONY : js_mat.s

# target to generate assembly for a file
js_mat.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_mat.cpp.s
.PHONY : js_mat.cpp.s

js_matx.o: js_matx.cpp.o
.PHONY : js_matx.o

# target to build an object file
js_matx.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_matx.cpp.o
.PHONY : js_matx.cpp.o

js_matx.i: js_matx.cpp.i
.PHONY : js_matx.i

# target to preprocess a source file
js_matx.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_matx.cpp.i
.PHONY : js_matx.cpp.i

js_matx.s: js_matx.cpp.s
.PHONY : js_matx.s

# target to generate assembly for a file
js_matx.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_matx.cpp.s
.PHONY : js_matx.cpp.s

js_opengl.o: js_opengl.cpp.o
.PHONY : js_opengl.o

# target to build an object file
js_opengl.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_opengl.cpp.o
.PHONY : js_opengl.cpp.o

js_opengl.i: js_opengl.cpp.i
.PHONY : js_opengl.i

# target to preprocess a source file
js_opengl.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_opengl.cpp.i
.PHONY : js_opengl.cpp.i

js_opengl.s: js_opengl.cpp.s
.PHONY : js_opengl.s

# target to generate assembly for a file
js_opengl.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_opengl.cpp.s
.PHONY : js_opengl.cpp.s

js_point.o: js_point.cpp.o
.PHONY : js_point.o

# target to build an object file
js_point.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_point.cpp.o
.PHONY : js_point.cpp.o

js_point.i: js_point.cpp.i
.PHONY : js_point.i

# target to preprocess a source file
js_point.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_point.cpp.i
.PHONY : js_point.cpp.i

js_point.s: js_point.cpp.s
.PHONY : js_point.s

# target to generate assembly for a file
js_point.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_point.cpp.s
.PHONY : js_point.cpp.s

js_point_iterator.o: js_point_iterator.cpp.o
.PHONY : js_point_iterator.o

# target to build an object file
js_point_iterator.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_point_iterator.cpp.o
.PHONY : js_point_iterator.cpp.o

js_point_iterator.i: js_point_iterator.cpp.i
.PHONY : js_point_iterator.i

# target to preprocess a source file
js_point_iterator.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_point_iterator.cpp.i
.PHONY : js_point_iterator.cpp.i

js_point_iterator.s: js_point_iterator.cpp.s
.PHONY : js_point_iterator.s

# target to generate assembly for a file
js_point_iterator.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_point_iterator.cpp.s
.PHONY : js_point_iterator.cpp.s

js_raspi_cam.o: js_raspi_cam.cpp.o
.PHONY : js_raspi_cam.o

# target to build an object file
js_raspi_cam.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_raspi_cam.cpp.o
.PHONY : js_raspi_cam.cpp.o

js_raspi_cam.i: js_raspi_cam.cpp.i
.PHONY : js_raspi_cam.i

# target to preprocess a source file
js_raspi_cam.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_raspi_cam.cpp.i
.PHONY : js_raspi_cam.cpp.i

js_raspi_cam.s: js_raspi_cam.cpp.s
.PHONY : js_raspi_cam.s

# target to generate assembly for a file
js_raspi_cam.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_raspi_cam.cpp.s
.PHONY : js_raspi_cam.cpp.s

js_rect.o: js_rect.cpp.o
.PHONY : js_rect.o

# target to build an object file
js_rect.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_rect.cpp.o
.PHONY : js_rect.cpp.o

js_rect.i: js_rect.cpp.i
.PHONY : js_rect.i

# target to preprocess a source file
js_rect.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_rect.cpp.i
.PHONY : js_rect.cpp.i

js_rect.s: js_rect.cpp.s
.PHONY : js_rect.s

# target to generate assembly for a file
js_rect.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_rect.cpp.s
.PHONY : js_rect.cpp.s

js_rotated_rect.o: js_rotated_rect.cpp.o
.PHONY : js_rotated_rect.o

# target to build an object file
js_rotated_rect.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_rotated_rect.cpp.o
.PHONY : js_rotated_rect.cpp.o

js_rotated_rect.i: js_rotated_rect.cpp.i
.PHONY : js_rotated_rect.i

# target to preprocess a source file
js_rotated_rect.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_rotated_rect.cpp.i
.PHONY : js_rotated_rect.cpp.i

js_rotated_rect.s: js_rotated_rect.cpp.s
.PHONY : js_rotated_rect.s

# target to generate assembly for a file
js_rotated_rect.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_rotated_rect.cpp.s
.PHONY : js_rotated_rect.cpp.s

js_size.o: js_size.cpp.o
.PHONY : js_size.o

# target to build an object file
js_size.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_size.cpp.o
.PHONY : js_size.cpp.o

js_size.i: js_size.cpp.i
.PHONY : js_size.i

# target to preprocess a source file
js_size.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_size.cpp.i
.PHONY : js_size.cpp.i

js_size.s: js_size.cpp.s
.PHONY : js_size.s

# target to generate assembly for a file
js_size.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_size.cpp.s
.PHONY : js_size.cpp.s

js_slice_iterator.o: js_slice_iterator.cpp.o
.PHONY : js_slice_iterator.o

# target to build an object file
js_slice_iterator.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_slice_iterator.cpp.o
.PHONY : js_slice_iterator.cpp.o

js_slice_iterator.i: js_slice_iterator.cpp.i
.PHONY : js_slice_iterator.i

# target to preprocess a source file
js_slice_iterator.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_slice_iterator.cpp.i
.PHONY : js_slice_iterator.cpp.i

js_slice_iterator.s: js_slice_iterator.cpp.s
.PHONY : js_slice_iterator.s

# target to generate assembly for a file
js_slice_iterator.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_slice_iterator.cpp.s
.PHONY : js_slice_iterator.cpp.s

js_subdiv2d.o: js_subdiv2d.cpp.o
.PHONY : js_subdiv2d.o

# target to build an object file
js_subdiv2d.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_subdiv2d.cpp.o
.PHONY : js_subdiv2d.cpp.o

js_subdiv2d.i: js_subdiv2d.cpp.i
.PHONY : js_subdiv2d.i

# target to preprocess a source file
js_subdiv2d.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_subdiv2d.cpp.i
.PHONY : js_subdiv2d.cpp.i

js_subdiv2d.s: js_subdiv2d.cpp.s
.PHONY : js_subdiv2d.s

# target to generate assembly for a file
js_subdiv2d.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_subdiv2d.cpp.s
.PHONY : js_subdiv2d.cpp.s

js_umat.o: js_umat.cpp.o
.PHONY : js_umat.o

# target to build an object file
js_umat.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_umat.cpp.o
.PHONY : js_umat.cpp.o

js_umat.i: js_umat.cpp.i
.PHONY : js_umat.i

# target to preprocess a source file
js_umat.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_umat.cpp.i
.PHONY : js_umat.cpp.i

js_umat.s: js_umat.cpp.s
.PHONY : js_umat.s

# target to generate assembly for a file
js_umat.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_umat.cpp.s
.PHONY : js_umat.cpp.s

js_utility.o: js_utility.cpp.o
.PHONY : js_utility.o

# target to build an object file
js_utility.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_utility.cpp.o
.PHONY : js_utility.cpp.o

js_utility.i: js_utility.cpp.i
.PHONY : js_utility.i

# target to preprocess a source file
js_utility.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_utility.cpp.i
.PHONY : js_utility.cpp.i

js_utility.s: js_utility.cpp.s
.PHONY : js_utility.s

# target to generate assembly for a file
js_utility.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_utility.cpp.s
.PHONY : js_utility.cpp.s

js_video_capture.o: js_video_capture.cpp.o
.PHONY : js_video_capture.o

# target to build an object file
js_video_capture.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_video_capture.cpp.o
.PHONY : js_video_capture.cpp.o

js_video_capture.i: js_video_capture.cpp.i
.PHONY : js_video_capture.i

# target to preprocess a source file
js_video_capture.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_video_capture.cpp.i
.PHONY : js_video_capture.cpp.i

js_video_capture.s: js_video_capture.cpp.s
.PHONY : js_video_capture.s

# target to generate assembly for a file
js_video_capture.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_video_capture.cpp.s
.PHONY : js_video_capture.cpp.s

js_video_writer.o: js_video_writer.cpp.o
.PHONY : js_video_writer.o

# target to build an object file
js_video_writer.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_video_writer.cpp.o
.PHONY : js_video_writer.cpp.o

js_video_writer.i: js_video_writer.cpp.i
.PHONY : js_video_writer.i

# target to preprocess a source file
js_video_writer.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_video_writer.cpp.i
.PHONY : js_video_writer.cpp.i

js_video_writer.s: js_video_writer.cpp.s
.PHONY : js_video_writer.s

# target to generate assembly for a file
js_video_writer.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_video_writer.cpp.s
.PHONY : js_video_writer.cpp.s

js_white_balancer.o: js_white_balancer.cpp.o
.PHONY : js_white_balancer.o

# target to build an object file
js_white_balancer.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_white_balancer.cpp.o
.PHONY : js_white_balancer.cpp.o

js_white_balancer.i: js_white_balancer.cpp.i
.PHONY : js_white_balancer.i

# target to preprocess a source file
js_white_balancer.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_white_balancer.cpp.i
.PHONY : js_white_balancer.cpp.i

js_white_balancer.s: js_white_balancer.cpp.s
.PHONY : js_white_balancer.s

# target to generate assembly for a file
js_white_balancer.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_white_balancer.cpp.s
.PHONY : js_white_balancer.cpp.s

js_ximgproc.o: js_ximgproc.cpp.o
.PHONY : js_ximgproc.o

# target to build an object file
js_ximgproc.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_ximgproc.cpp.o
.PHONY : js_ximgproc.cpp.o

js_ximgproc.i: js_ximgproc.cpp.i
.PHONY : js_ximgproc.i

# target to preprocess a source file
js_ximgproc.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_ximgproc.cpp.i
.PHONY : js_ximgproc.cpp.i

js_ximgproc.s: js_ximgproc.cpp.s
.PHONY : js_ximgproc.s

# target to generate assembly for a file
js_ximgproc.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/js_ximgproc.cpp.s
.PHONY : js_ximgproc.cpp.s

lsd/src/lsd.o: lsd/src/lsd.cpp.o
.PHONY : lsd/src/lsd.o

# target to build an object file
lsd/src/lsd.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd.cpp.o
.PHONY : lsd/src/lsd.cpp.o

lsd/src/lsd.i: lsd/src/lsd.cpp.i
.PHONY : lsd/src/lsd.i

# target to preprocess a source file
lsd/src/lsd.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd.cpp.i
.PHONY : lsd/src/lsd.cpp.i

lsd/src/lsd.s: lsd/src/lsd.cpp.s
.PHONY : lsd/src/lsd.s

# target to generate assembly for a file
lsd/src/lsd.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd.cpp.s
.PHONY : lsd/src/lsd.cpp.s

lsd/src/lsd_opencv.o: lsd/src/lsd_opencv.cpp.o
.PHONY : lsd/src/lsd_opencv.o

# target to build an object file
lsd/src/lsd_opencv.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd_opencv.cpp.o
.PHONY : lsd/src/lsd_opencv.cpp.o

lsd/src/lsd_opencv.i: lsd/src/lsd_opencv.cpp.i
.PHONY : lsd/src/lsd_opencv.i

# target to preprocess a source file
lsd/src/lsd_opencv.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd_opencv.cpp.i
.PHONY : lsd/src/lsd_opencv.cpp.i

lsd/src/lsd_opencv.s: lsd/src/lsd_opencv.cpp.s
.PHONY : lsd/src/lsd_opencv.s

# target to generate assembly for a file
lsd/src/lsd_opencv.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd_opencv.cpp.s
.PHONY : lsd/src/lsd_opencv.cpp.s

lsd/src/lsd_wrap.o: lsd/src/lsd_wrap.cpp.o
.PHONY : lsd/src/lsd_wrap.o

# target to build an object file
lsd/src/lsd_wrap.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd_wrap.cpp.o
.PHONY : lsd/src/lsd_wrap.cpp.o

lsd/src/lsd_wrap.i: lsd/src/lsd_wrap.cpp.i
.PHONY : lsd/src/lsd_wrap.i

# target to preprocess a source file
lsd/src/lsd_wrap.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd_wrap.cpp.i
.PHONY : lsd/src/lsd_wrap.cpp.i

lsd/src/lsd_wrap.s: lsd/src/lsd_wrap.cpp.s
.PHONY : lsd/src/lsd_wrap.s

# target to generate assembly for a file
lsd/src/lsd_wrap.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/lsd/src/lsd_wrap.cpp.s
.PHONY : lsd/src/lsd_wrap.cpp.s

src/geometry.o: src/geometry.cpp.o
.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i
.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s
.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/init_module.o: src/init_module.cpp.o
.PHONY : src/init_module.o

# target to build an object file
src/init_module.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/init_module.cpp.o
.PHONY : src/init_module.cpp.o

src/init_module.i: src/init_module.cpp.i
.PHONY : src/init_module.i

# target to preprocess a source file
src/init_module.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/init_module.cpp.i
.PHONY : src/init_module.cpp.i

src/init_module.s: src/init_module.cpp.s
.PHONY : src/init_module.s

# target to generate assembly for a file
src/init_module.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/init_module.cpp.s
.PHONY : src/init_module.cpp.s

src/jsbindings.o: src/jsbindings.cpp.o
.PHONY : src/jsbindings.o

# target to build an object file
src/jsbindings.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/jsbindings.cpp.o
.PHONY : src/jsbindings.cpp.o

src/jsbindings.i: src/jsbindings.cpp.i
.PHONY : src/jsbindings.i

# target to preprocess a source file
src/jsbindings.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/jsbindings.cpp.i
.PHONY : src/jsbindings.cpp.i

src/jsbindings.s: src/jsbindings.cpp.s
.PHONY : src/jsbindings.s

# target to generate assembly for a file
src/jsbindings.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/jsbindings.cpp.s
.PHONY : src/jsbindings.cpp.s

src/line.o: src/line.cpp.o
.PHONY : src/line.o

# target to build an object file
src/line.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/line.cpp.o
.PHONY : src/line.cpp.o

src/line.i: src/line.cpp.i
.PHONY : src/line.i

# target to preprocess a source file
src/line.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/line.cpp.i
.PHONY : src/line.cpp.i

src/line.s: src/line.cpp.s
.PHONY : src/line.s

# target to generate assembly for a file
src/line.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/line.cpp.s
.PHONY : src/line.cpp.s

src/util.o: src/util.cpp.o
.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	cd /home/roman/Projects/plot-cv && $(MAKE) $(MAKESILENT) -f qjs-opencv/CMakeFiles/quickjs-opencv.dir/build.make qjs-opencv/CMakeFiles/quickjs-opencv.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... quickjs-opencv"
	@echo "... algorithms/dominant_colors_grabber.o"
	@echo "... algorithms/dominant_colors_grabber.i"
	@echo "... algorithms/dominant_colors_grabber.s"
	@echo "... gifenc/gifenc.o"
	@echo "... gifenc/gifenc.i"
	@echo "... gifenc/gifenc.s"
	@echo "... js_affine3.o"
	@echo "... js_affine3.i"
	@echo "... js_affine3.s"
	@echo "... js_algorithms.o"
	@echo "... js_algorithms.i"
	@echo "... js_algorithms.s"
	@echo "... js_aruco.o"
	@echo "... js_aruco.i"
	@echo "... js_aruco.s"
	@echo "... js_barcode_detector.o"
	@echo "... js_barcode_detector.i"
	@echo "... js_barcode_detector.s"
	@echo "... js_bg_subtractor.o"
	@echo "... js_bg_subtractor.i"
	@echo "... js_bg_subtractor.s"
	@echo "... js_calib3d.o"
	@echo "... js_calib3d.i"
	@echo "... js_calib3d.s"
	@echo "... js_clahe.o"
	@echo "... js_clahe.i"
	@echo "... js_clahe.s"
	@echo "... js_contour.o"
	@echo "... js_contour.i"
	@echo "... js_contour.s"
	@echo "... js_cv.o"
	@echo "... js_cv.i"
	@echo "... js_cv.s"
	@echo "... js_draw.o"
	@echo "... js_draw.i"
	@echo "... js_draw.s"
	@echo "... js_fast_line_detector.o"
	@echo "... js_fast_line_detector.i"
	@echo "... js_fast_line_detector.s"
	@echo "... js_feature2d.o"
	@echo "... js_feature2d.i"
	@echo "... js_feature2d.s"
	@echo "... js_filenode.o"
	@echo "... js_filenode.i"
	@echo "... js_filenode.s"
	@echo "... js_filestorage.o"
	@echo "... js_filestorage.i"
	@echo "... js_filestorage.s"
	@echo "... js_fisheye.o"
	@echo "... js_fisheye.i"
	@echo "... js_fisheye.s"
	@echo "... js_highgui.o"
	@echo "... js_highgui.i"
	@echo "... js_highgui.s"
	@echo "... js_imgproc.o"
	@echo "... js_imgproc.i"
	@echo "... js_imgproc.s"
	@echo "... js_keypoint.o"
	@echo "... js_keypoint.i"
	@echo "... js_keypoint.s"
	@echo "... js_libcamera_app.o"
	@echo "... js_libcamera_app.i"
	@echo "... js_libcamera_app.s"
	@echo "... js_line.o"
	@echo "... js_line.i"
	@echo "... js_line.s"
	@echo "... js_line_iterator.o"
	@echo "... js_line_iterator.i"
	@echo "... js_line_iterator.s"
	@echo "... js_line_segment_detector.o"
	@echo "... js_line_segment_detector.i"
	@echo "... js_line_segment_detector.s"
	@echo "... js_mat.o"
	@echo "... js_mat.i"
	@echo "... js_mat.s"
	@echo "... js_matx.o"
	@echo "... js_matx.i"
	@echo "... js_matx.s"
	@echo "... js_opengl.o"
	@echo "... js_opengl.i"
	@echo "... js_opengl.s"
	@echo "... js_point.o"
	@echo "... js_point.i"
	@echo "... js_point.s"
	@echo "... js_point_iterator.o"
	@echo "... js_point_iterator.i"
	@echo "... js_point_iterator.s"
	@echo "... js_raspi_cam.o"
	@echo "... js_raspi_cam.i"
	@echo "... js_raspi_cam.s"
	@echo "... js_rect.o"
	@echo "... js_rect.i"
	@echo "... js_rect.s"
	@echo "... js_rotated_rect.o"
	@echo "... js_rotated_rect.i"
	@echo "... js_rotated_rect.s"
	@echo "... js_size.o"
	@echo "... js_size.i"
	@echo "... js_size.s"
	@echo "... js_slice_iterator.o"
	@echo "... js_slice_iterator.i"
	@echo "... js_slice_iterator.s"
	@echo "... js_subdiv2d.o"
	@echo "... js_subdiv2d.i"
	@echo "... js_subdiv2d.s"
	@echo "... js_umat.o"
	@echo "... js_umat.i"
	@echo "... js_umat.s"
	@echo "... js_utility.o"
	@echo "... js_utility.i"
	@echo "... js_utility.s"
	@echo "... js_video_capture.o"
	@echo "... js_video_capture.i"
	@echo "... js_video_capture.s"
	@echo "... js_video_writer.o"
	@echo "... js_video_writer.i"
	@echo "... js_video_writer.s"
	@echo "... js_white_balancer.o"
	@echo "... js_white_balancer.i"
	@echo "... js_white_balancer.s"
	@echo "... js_ximgproc.o"
	@echo "... js_ximgproc.i"
	@echo "... js_ximgproc.s"
	@echo "... lsd/src/lsd.o"
	@echo "... lsd/src/lsd.i"
	@echo "... lsd/src/lsd.s"
	@echo "... lsd/src/lsd_opencv.o"
	@echo "... lsd/src/lsd_opencv.i"
	@echo "... lsd/src/lsd_opencv.s"
	@echo "... lsd/src/lsd_wrap.o"
	@echo "... lsd/src/lsd_wrap.i"
	@echo "... lsd/src/lsd_wrap.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/init_module.o"
	@echo "... src/init_module.i"
	@echo "... src/init_module.s"
	@echo "... src/jsbindings.o"
	@echo "... src/jsbindings.i"
	@echo "... src/jsbindings.s"
	@echo "... src/line.o"
	@echo "... src/line.i"
	@echo "... src/line.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -P /home/roman/Projects/plot-cv/CMakeFiles/VerifyGlobs.cmake
	cd /home/roman/Projects/plot-cv && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

